config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_variables

  # examples to run with, we'll see how well they work
  def development?
    Rails.env.development?
  end

  def test?
    Rails.env.test?
  end

  def production?
    Rails.env.production?
  end

  def set_variables
    @application_links = application_links
    @external_links = default_external_links #current_app.nil? ? default_external_links : app_specific_external_links
  end

  def application_links
    [
        {
            name: 'Sample Domain',
            desc: 'The main example of an application link.',
            id: 'sample-domain'
        }
    ]
  end

  def default_external_links
    [
        { name: 'Gabe\'s Github', url: 'https://github.com/genslein' }
    ]
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body, :time_posted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.haml
= form_for @blog_post do |f|
  - if @blog_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog_post.errors.count, "error")} prohibited this blog_post from being saved:"
      %ul
        - @blog_post.errors.full_messages.each do |msg|
          %li= msg

  .row.collapse
    .small-3.columns
    = f.label :title, class: 'right inline'
    .small-9.columns
    = f.text_area :title
  .row.collapse
    .small-3.columns
    = f.label :body, class: 'right inline', title: "Content to Publish", data: {tooltip: true}
    .small-9.columns
    = f.text_area :body
  .row.collapse
    .small-3.columns
    = f.label :time_posted, class: 'right inline'
    .small-9.columns
    = f.datetime_select :time_posted
  .row.collapse
    .small-9.small-offset-3.columns
    = f.submit 'Save', class: 'button radius'

app/views/blog_posts/edit.html.haml
%h1 Editing blog_post

= render 'form'

= link_to 'Show', @blog_post
\|
= link_to 'Back', blog_posts_path

app/views/blog_posts/index.html.haml
%h1 Listing Blog Posts

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Time posted
      %th
      %th
      %th

  %tbody
    - @blog_posts.each do |blog_post|
      %tr
        %td= blog_post.title
        %td= blog_post.body
        %td= blog_post.time_posted
        %td= link_to 'Show', blog_post
        %td= link_to 'Edit', edit_blog_post_path(blog_post)
        %td= link_to 'Destroy', blog_post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Blog post', new_blog_post_path, class: 'button radius'

app/views/blog_posts/new.html.haml
%h1 New Blog Post

= render 'form'
= link_to 'Back', blog_posts_path, class: 'button radius'

app/views/blog_posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @blog_post.title
%p
  %b Body:
  = @blog_post.body
%p
  %b Time posted:
  = @blog_post.time_posted

= link_to 'Edit', edit_blog_post_path(@blog_post)
\|
= link_to 'Back', blog_posts_path

app/views/layouts/_header.haml
.title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "header-menu"}
  %button.menu-icon{"data-toggle" => "", :type => "button"}
  .title-bar-title Menu
#header-menu.top-bar
  .top-bar-left
    %ul.dropdown.menu{"data-dropdown-menu" => ""}
      %li.menu-text Site Title
      %li.has-submenu
        %a{:href => "#"} One
        %ul.submenu.menu.vertical{"data-submenu" => ""}
          %li
            %a{:href => "#"} One
          %li
            %a{:href => "#"} Two
          %li
            %a{:href => "#"} Three
      %li
        %a{:href => "#"} Two
      %li
        %a{:href => "#"} Three
  .top-bar-right
    %ul.menu
      %li
        %input{:placeholder => "Search", :type => "search"}/
      %li
        %button.button{:type => "button"} Search

app/views/layouts/_sidebar.haml
.title-bar{"data-hide-for" => "all", "data-responsive-toggle" => "side-menu"}
  %button.menu-icon{"data-toggle" => "", :type => "button"}
  .title-bar-title External Links

#side-menu.sidebar
  %ul.dropdown.menu.vertical{"data-dropdown-menu" => ""}
    %li.has-submenu
      %a{:href => "#"} Personal Links
      %ul.submenu.menu.vertical{"data-submenu" => ""}
        -@external_links.each do |link|
          %li=link_to link[:name], link[:url], :target => "_blank"
    %li.has-submenu
      %a{:href => "#"} Applications
      %ul.submenu.menu.vertical{"data-submenu" => ""}
        -@application_links.each do |link|
          %li=link_to link[:name], link[:url], :target => "_blank" #main_app.app_path(id: link[:id])
    %li.has-submenu
      %a{:href => "#"} Help Links
      %ul.submenu.menu.vertical{"data-submenu" => ""}
        %li=link_to 'First Chart', image_path('special_image.png')
        %li=link_to 'Second Chart', image_path('special_chart.png')

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body
    = render 'layouts/header'
    .large-2.large-left.columns=render 'layouts/sidebar'
    .medium-9.medium-left.large-10.columns= content_for?(:content) ? yield(:content) : yield
    = javascript_include_tag "application"
    = yield :javascript